### ISSUE TITLE
WireFrame

### ISSUE THREAD

**Issue by HerikPavan** [SouJunior/Site#11]

**Comment by thaygjo** [comment]
aqui

**Comment by thaygjo** [comment]
Segue imagens do protótipo de alta fidelidade o link para acesso é o mesmo já citado acima.

https://www.figma.com/file/9FZH7FhqQt3cqFNASY2q8F/Wireframe-Site?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/86688624/196171306-059915d7-3ceb-4205-9eb8-d1446bb6bd8e.png)
![Image](https://user-images.githubusercontent.com/86688624/196171307-8ad5e5a8-0cdb-45ab-a4f8-05881eedfbe0.png)

**Comment by edcabralc** [comment]
@thaygjo, você irá atualizar essa Issue com as alterações?
