### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by JaymeGabriel** [SouJunior/Site#72]
Fala, pessoal! Tudo bem?
Vi que o site está para ser lançado, já está no ar e etc. Como estou migrando para a área de UX/UI e não conhecia o projeto do site, fui dar uma olhada e trouxe alguns pontos que talvez interesse a vocês. @wouerner me passou esse canal para postar aqui. Espero que seja de alguma ajuda e parabéns pelo projeto! 👊👏

Link: https://www.figma.com/proto/C7kfbzzXNzXswoom4QntDx?node-id=0:1&comments-enabled=1

O arquivo está no figma, não tenho o PDF aqui no celular. 😁

**Comment by edcabralc** [comment]
@JaymeGabriel ótimas observações! Já atualizamos e corrigimos alguns pontos de acordo com o que você apontou. Em breve atualizaremos o restante. É muito importante o feedback, para o nosso aprendizado. Obrigado!
